
all:  ../../bin/execfile ../../bin/startdiscretaq

../../bin/execfile: execfile.C
	g++ -o ../../bin/execfile execfile.C

../../bin/startdiscretaq: start.C
	g++ -o ../../bin/startdiscretaq start.C

clean:
	rm -f ../../bin/execfile ../../bin/startdiscretaq


