install:
	cd sources/dqbase && make && cd ../../ && \
	cd sources/lll && make && cd ../../ && \
	cd sources/dance && make && cd ../../ && \
	cd sources/tcltk && make && cd ../../

clean:
	cd sources/dqbase && make clean && cd ../../ && \
	cd sources/lll && make clean && cd ../../ && \
	cd sources/dance && make clean && cd ../../ && \
	cd sources/tcltk && make && cd ../../


